### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by k4kfh** [3dprinteros/OctoPrint-3DPrinterOS#2]
I noticed this is not publicized much on the 3DprinterOS website, and it's not listed in the OctoPrint plugin repo. Is this project dead?

**Comment by KMVPrograms** [comment]
Hello. No, it is not dead. It is listed in 3DPrinterOS Cloud here: https://cloud.3dprinteros.com/download/#cloud-plugins (OTHER PLUGINS)
